next-app-with-locales:
  component: "@sls-next/serverless-component@3.3.0-alpha.1"
  inputs:
    build:
      postBuildCommands: ["node scripts/post-build-test.js"]
    cloudfront:
      defaults:
        forward:
          headers: [Authorization, Accept-Language]
      api/*:
        forward:
          headers: [Authorization]
