name: Release stable version

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who triggered this?"
        required: true

jobs:
  build:
    runs-on: [ubuntu-latest]
    name: "Release stable version"
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: yarn install
      - run: GH_TOKEN=${{secrets.GH_TOKEN}} yarn graduate
